-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
-- require('plugins.neotree')
require('plugins.treesitter')
require('plugins.fluttertools')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.autopairs')
-- require('plugins.dashboard')
-- require('plugins.buffline')
-- require('plugins.comments')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.toggleterm')
-- require('plugins.catppuccin')
-- require('plugins.colortils')
